# Numpy Matrix Tutorial

In [2]:
# Importing Numpy Package 
import numpy as np

Let's start with defining matrix. There are multiple ways of creating a matrix using numpy
package. We will see how to define a same matrix using multiple methods.

In [55]:
"""Defining two matricies of shape (2,3) Two Rows and Three Columns 

There are two ways of defining a matrix in python.

This is the more popular way of defining a matrix by creating a 1D array and then 
converting it into a matrix.
"""

print "----This is the first way----"

matA = np.arange(6).reshape(2,3)
matB = np.arange(10,16).reshape(3,2)

print "Printing Matrix A"
print matA
print "Printing Matrix B"
print matB

print "Shape of Matrix A: ",matA.shape
print "Shape of Matrix B: ",matB.shape

"""
The other less popular way of defining a matrix is by calling 
builtin np.matrix function.

There are two ways the function can be called.

First way, by passing the string argument where rows are delimited by ;
"""

print "----This is the second way----"

matA = np.matrix('1 2 3;4 5 6')
matB = np.matrix('10 11;12 13;14 15')

print "Printing Matrix A"
print matA
print "Printing Matrix B"
print matB

print "Shape of Matrix A: ",matA.shape
print "Shape of Matrix B: ",matB.shape


# Second way, by passing nested list of rows
print "----This is the third way----"

matA = np.matrix([[1,2,3],[4,5,6]])
matB = np.matrix([[10,11],[12,13],[14,15]])

print "Printing Matrix A"
print matA
print "Printing Matrix B"
print matB

print "Shape of Matrix A: ",matA.shape
print "Shape of Matrix B: ",matB.shape

print "---------------------"

----This is the first way----
Printing Matrix A
[[0 1 2]
 [3 4 5]]
Printing Matrix B
[[10 11]
 [12 13]
 [14 15]]
Shape of Matrix A:  (2L, 3L)
Shape of Matrix B:  (3L, 2L)
----This is the second way----
Printing Matrix A
[[1 2 3]
 [4 5 6]]
Printing Matrix B
[[10 11]
 [12 13]
 [14 15]]
Shape of Matrix A:  (2L, 3L)
Shape of Matrix B:  (3L, 2L)
----This is the third way----
Printing Matrix A
[[1 2 3]
 [4 5 6]]
Printing Matrix B
[[10 11]
 [12 13]
 [14 15]]
Shape of Matrix A:  (2L, 3L)
Shape of Matrix B:  (3L, 2L)
---------------------


After defining the matrix, manytime there are few information about the matrix you need 
to verify. For example:
    1. Size of the matrix
    2. Shape of the matrix
    3. Dimensions of the matrix
    4. Data type of the matrix formed
    5. Total Bytes consumed by the matrix

In [97]:
# Let's start with how the matrix looks like

print "Matrix A: "
print matA

print "\nSize of the Matrix: ", matA.size

print "\nShape of the Matrix: ",matA.shape

print "\nDimensions of the Matrix: ", matA.ndim

print "\nData Type of the Matrix: ", matA.dtype

print "\nTotal size of the Matrix (In Bytes): ", matA.nbytes

Matrix A: 
[[1 2 3]
 [4 5 6]]

Size of the Matrix:  6

Shape of the Matrix:  (2L, 3L)

Dimensions of the Matrix:  2

Data Type of the Matrix:  int32

Total size of the Matrix (In Bytes):  24


As we can create a matrix from a 1D array by reshaping it, we can create 1D array from the matrix.

In [98]:
print "Matrix A: "
print matA

# By Attribute
print "\n1D Array from the matrix (By Attribute): "
print matA.A1

#By Function
print "\n1D Array from the matrix (By Function): "
print matA.getA1()
print matA.flatten()


# We can also create a flat iterator object from the matrix similar to 1D array.

matAFlat = matA.flat
print "\nShowing the type of flat iterator object: ",type(matAFlat)
print "\nPrinting Elements: "
for i in matAFlat:
    print i

print "\nWe can also use ravel() function to convert the matrix to a flattened array"
print matA.ravel()


Matrix A: 
[[1 2 3]
 [4 5 6]]

1D Array from the matrix (By Attribute): 
[1 2 3 4 5 6]

1D Array from the matrix (By Function): 
[1 2 3 4 5 6]
[[1 2 3 4 5 6]]

Showing the type of flat iterator object:  <type 'numpy.flatiter'>

Printing Elements: 
1
2
3
4
5
6

We can also use ravel() function to convert the matrix to a flattened array
[[1 2 3 4 5 6]]


Now let's explore how we can get basic details like:
    1. Max/Min value of the matrix
    2. Index of max/min value in the matrix
    4. Sum of all values of the matrix
    5. Sum of values across rows/columns

In [132]:
print matA

print "\n--Matrix level operations--"
print "\nMax Value of the matrix: ",matA.max()
print "\nMin Value of the matrix: ",matA.min()
print "\nIndex of max value in the matrix: ",matA.argmax()
print "\nIndex of min value in the matrix: ",matA.argmin()
print "\nSum of all elements in the matrix: ",matA.sum()
print "\nStandard Deviation of the matrix: ",matA.std()
print "\nMean of the matrix: ",matA.mean()
print "\nCumulative Sum along column and row: "
print "Along Row"
print matA.cumsum(axis = 0)
print "Along Column"
print matA.cumsum(axis = 1)
print "\nCumulative Product along column and row: "
print "Along Row"
print matA.cumprod(axis = 0)
print "Along Column"
print matA.cumprod(axis = 1)


print "\n--Row/Column/Diagonal level operation--"
print "\nMax Value of the matrix along the column: ",matA.max(axis= 0)
print "\nMin Value of the matrix along the row: ",matA.min(axis = 1)
print "\nIndex of max value in the matrix along the column: ",matA.argmax(axis = 0)
print "\nIndex of min value in the matrix along the row: ",matA.argmin(axis = 1)


"""
Columnwise and rowise sum of elements

Axis = 0 for columns 
Axis = 1 for rows 

Note: Opposite of Pandas 
"""
print "\nPrint Columns Sum: ",matA.sum(axis = 0)
print "\nRows Sum: "
print matA.sum(axis = 1)

[[1 2 3]
 [4 5 6]]

--Matrix level operations--

Max Value of the matrix:  6

Min Value of the matrix:  1

Index of max value in the matrix:  5

Index of min value in the matrix:  0

Sum of all elements in the matrix:  21

Standard Deviation of the matrix:  1.70782512766

Mean of the matrix:  3.5

Cumulative Sum along column and row: 
Along Row
[[1 2 3]
 [5 7 9]]
Along Column
[[ 1  3  6]
 [ 4  9 15]]

Cumulative Product along column and row: 
Along Row
[[ 1  2  3]
 [ 4 10 18]]
Along Column
[[  1   2   6]
 [  4  20 120]]

--Row/Column/Diagonal level operation--

Max Value of the matrix along the column:  [[4 5 6]]

Min Value of the matrix along the row:  [[1]
 [4]]

Index of max value in the matrix along the column:  [[1 1 1]]

Index of min value in the matrix along the row:  [[0]
 [0]]

Print Columns Sum:  [[5 7 9]]

Rows Sum: 
[[ 6]
 [15]]


In this section, we will explore how we can sort elements in the matrix. We can do this
at matrix level as well as at rows/columns level

In [142]:
matC = np.matrix([[4,2,6],[43,12,56]])

print "--Matrix Level Sorting--"
print np.sort(matC)

print "\n--Row/Column Level Sorting--"
print "\nColumn Wise Sorting"
print np.sort(matC,axis = 0)
print "\nRow Wise Sorting"
print np.sort(matC,axis = 1)



# We can also get indexes of the sorted matrix both at matrix level as well as at 
# row/column level. We can use np.argsort() for this. 


# print np.argsort(matC,axis = 1)


# We can get index of all non zero values in the matrix using nonzero function.

# print matC.nonzero()

--Matrix Level Sorting--
[[ 2  4  6]
 [12 43 56]]

--Row/Column Level Sorting--

Column Wise Sorting
[[ 4  2  6]
 [43 12 56]]

Row Wise Sorting
[[ 2  4  6]
 [12 43 56]]


In [70]:
# Matrix Transpose 

# Three Methods of Transposing a matrix in numpy

print "Matrix Transpose"

matATranspose = matA.T
print matATranspose

print "-------"

matATranspose = matA.transpose()
print matATranspose

print "-------"

matATranspose = np.transpose(matA)
print matATranspose

print "-------"
matATranspose = matA.getT()
print matATranspose

print ""
print "Conjucate Transpose of a matrix"

"""
Transpose of a matrix is obtained by rearranging columns into rows, or rows into columns. 
The complex conjugate of a matrix is obtained by replacing each element by its 
complex conjugate (i.e x+iy ⇛ x-iy or vice versa). The conjugate transpose is obtained 
by performing both operations on the matrix.
"""

matD = np.matrix([[3+2j,3+3j],[2+3j,5+6j]])
print "\nComplex Matrix"
print matD
print "\nConjucate Transpose of the complex matrix"

# By Attribute
print matD.H
print "----"

# By calling function, this is complex conjuct element-wise operation
print matD.conjugate()

# By calling function, this is complex conjugate of all the elements
print matA.conj()


Matrix Transpose
[[1 4]
 [2 5]
 [3 6]]
-------
[[1 4]
 [2 5]
 [3 6]]
-------
[[1 4]
 [2 5]
 [3 6]]
-------
[[1 4]
 [2 5]
 [3 6]]

Conjucate Transpose of a matrix

Complex Matrix
[[ 3.+2.j  3.+3.j]
 [ 2.+3.j  5.+6.j]]

Conjucate Transpose of the complex matrix
[[ 3.-2.j  2.-3.j]
 [ 3.-3.j  5.-6.j]]
----
[[ 3.-2.j  3.-3.j]
 [ 2.-3.j  5.-6.j]]


Misc. Matrix Operations:
    1. Cliping
    2.

In [118]:
print matA

print "\nCliping"

"""
Given an interval, values outside the interval are clipped to the interval edges. 
For example, if an interval of [0, 1] is specified, values smaller than 0 become 0, 
and values larger than 1 become 1.
"""
print matA.clip(2,3)

[[1 2 3]
 [4 5 6]]

Cliping
[[2 2 3]
 [3 3 3]]


Matrix operations: 
    1. Matrix Addition
    2. Matrix Substraction
    3. Matrix Multiplication
    4. Matrix Division

The way I approach this section is, first I will do (matrix,matrix) level operations then will do (matrix,scaler) level operations also known as Broadcasting. 

In [173]:
scalerValue = 100

print "Printing Matrix A and B"
print matA
print "-----"
print matB

print "\n\n--Matrix Addition--"

print "\n(Matrix,Matrix) Level Operation"
print "Approach 1 (Using Unary Operation):"
assert matA.shape == matB.T.shape
matC = matA+matB.T
print matC

print "Approach 2 (Using np.add()):"
matC = np.add(matA,matB.T)
print matC


print "\n(Matrix,Scaler) Level Operation"
print "Approach 1 (Using Unary Operation):"
matC = matA+scalerValue
print matC

print "Approach 2 (Using np.add()):"
matC = np.add(matA,scalerValue)
print matC


print "\n\n--Matrix Subtraction--"

print "\n(Matrix,Matrix) Level Operation"
print "Approach 1 (Using Unary Operation):"
assert matA.shape == matB.T.shape
matC = matA-matB.T
print matC

print "Approach 2 (Using np.subtract()):"
matC = np.subtract(matA,matB.T)
print matC


print "\n(Matrix,Scaler) Level Operation"
print "Approach 1 (Using Unary Operation):"
matC = matA-scalerValue
print matC

print "Approach 2 (Using np.subtract()):"
matC = np.subtract(matA,scalerValue)
print matC

print "\n\n--Matrix Multiplication--"

print "\n(Matrix,Matrix) Level Operation"
print "Approach 1 (Using Unary Operation):"
assert matA.shape == matB.T.shape
matC = matA*matB
print matC

print "Approach 2 (Using np.dot()):"
matC = np.dot(matA,matB)
print matC

print "\n(Matrix,Scaler) Level Operation"
print "Approach 1 (Using Unary Operation):"
matC = matA*scalerValue
print matC

print "Approach 2 (Using np.dot()):"
matC = np.dot(matA,scalerValue)
print matC

print "\n\n--Matrix Subtraction--"

print "\n(Matrix,Matrix) Level Operation"
print "Approach 1 (Using Unary Operation):"
assert matA.shape == matB.T.shape
matC = matA-matB.T
print matC

print "Approach 2 (Using np.subtract()):"
matC = np.subtract(matA,matB.T)
print matC


print "\n(Matrix,Scaler) Level Operation"
print "Approach 1 (Using Unary Operation):"
matC = matA-scalerValue
print matC

print "Approach 2 (Using np.subtract()):"
matC = np.subtract(matA,scalerValue)
print matC

print "\n\n--Matrix Division--"

print "\n(Matrix,Matrix) Level Operation"
print "Approach 1 (Using Unary Operation):"
assert matA.shape == matB.T.shape
matC = matA//matB.T
print matC

print "Approach 2 (Using np.divide()):"
matC = np.divide(matA,matB.T)
print matC

print "\n(Matrix,Scaler) Level Operation"
print "Approach 1 (Using Unary Operation):"
matC = matA//scalerValue
print matC

print "Approach 2 (Using np.divide()):"
matC = np.divide(matA,scalerValue)
print matC

Printing Matrix A and B
[[1 2 3]
 [4 5 6]]
-----
[[10 11]
 [12 13]
 [14 15]]


--Matrix Addition--

(Matrix,Matrix) Level Operation
Approach 1 (Using Unary Operation):
[[11 14 17]
 [15 18 21]]
Approach 2 (Using np.add()):
[[11 14 17]
 [15 18 21]]

(Matrix,Scaler) Level Operation
Approach 1 (Using Unary Operation):
[[101 102 103]
 [104 105 106]]
Approach 2 (Using np.add()):
[[101 102 103]
 [104 105 106]]


--Matrix Subtraction--

(Matrix,Matrix) Level Operation
Approach 1 (Using Unary Operation):
[[ -9 -10 -11]
 [ -7  -8  -9]]
Approach 2 (Using np.subtract()):
[[ -9 -10 -11]
 [ -7  -8  -9]]

(Matrix,Scaler) Level Operation
Approach 1 (Using Unary Operation):
[[-99 -98 -97]
 [-96 -95 -94]]
Approach 2 (Using np.subtract()):
[[-99 -98 -97]
 [-96 -95 -94]]


--Matrix Multiplication--

(Matrix,Matrix) Level Operation
Approach 1 (Using Unary Operation):
[[ 76  82]
 [184 199]]
Approach 2 (Using np.dot()):
[[ 76  82]
 [184 199]]

(Matrix,Scaler) Level Operation
Approach 1 (Using Unary Operation